### PR TITLE
Update faq.rst

### PR DESCRIPTION
**Pull request by perzeababa**
added subsequent 'reload' command on console after installing a plugin.

### CODE REVIEW

**Comment by PEMapModder** [comment]
Reloading wouldn't unload plugins or update plugins. This is misleading.

**Comment by perzeababa** [comment]
this is not about unloading or updating plugins. I noticed that when you download a plugin .phar file, when you save that file to the plugins folder, the plugin doesn't get enabled unless you issue the reload command.

**Comment by shoghicp** [comment]
PocketMine doesn't continuously check. You have either to stop or issue reload, but doing reload can cause lots of issues with other plugins.

**Comment by perzeababa** [comment]
thanks.

**Comment by PEMapModder** [comment]
I didn't say it would reload new versions of plugins, but it is misleading to say this.

**Pull request closed without merging**
